### ISSUE TITLE
Add tags support

### ISSUE THREAD

**Issue by roman-holovin** [guilhem/docker-vagrant-ubuntu#1]
Can you add ubuntu tags to get needed base version please?

**Comment by guilhem** [comment]
hi @dantix 
Of course that will be awesome and in my Roadmap! :)

For the moment I'm building images directly from index.docker.io and it doesn't support multiple build for each tag. I will put an issue for this ;)

**Comment by guilhem** [comment]
@dantix done for 10.04 12.04 14.04 ;)
